mainhome/routes.py
import datetime
import os
#import flask
from flask import Flask, send_from_directory, render_template
from flask import Blueprint

app_000 = Blueprint('app_000', __name__, template_folder='templates', static_folder='static')

@app_000.route('/')
def first_home_page():
    return render_template('mainhome/index.html')

#if __name__ == '__main__':
#    app.run(host='127.0.0.1', port=8080, debug=True)

mainhome/templates/mainhome/index.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-uWxY/CJNBR+1zjPWmfnSnVxwRheevXITnMqoEIeG1LJrdI0GlVs/9cVSyPYXdcSF" crossorigin="anonymous">

    <title>程 式 集</title>
    <script src="{{ url_for('static', filename='/mainhome/script.js') }}"></script>
    <link type="text/css" rel="stylesheet" href="{{ url_for('static', filename='/mainhome/style.css') }}">

  </head>

  <body>
    <nav class="navbar navbar-expand-md navbar-dark bg-dark">

        <a class="navbar-brand" href="{{ url_for('app_000.first_home_page') }}">程 式 集</a>

        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    <a class="nav-link" href="{{ url_for('app_000.first_home_page') }}">主 頁<span class="sr-only"></span></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('app_001.tt_index_page') }}">時 間 表</a>
                </li>
            </ul>
        </div>

    </nav>



    <img src="/static/images/149.jpg" alt="This is an animated gif image, but it does not move"/>

    <h1>this page is not ready</h1>

  </body>

  <style>
    body {
        background-color: #212121;
        color: white
    }
  </style>


</html>