timetable/routes.py
import datetime
import os
#import flask
from flask import Flask, send_from_directory, render_template
from flask import Blueprint

app_001 = Blueprint('app_001', __name__, template_folder='templates', static_folder='static')

@app_001.route('/tt')
def tt_index_page():
    return render_template('timetable/tt_index.html')

@app_001.route('/tt_dic_index')
def tt_dic_page():
    return render_template('timetable/tt_dic_index.html')

@app_001.route('/tt_cic_index')
def tt_cic_page():
    return render_template('timetable/tt_cic_index.html')

@app_001.route('/pdf_files/tt/ccbt21001.pdf') #the url you'll send the user to when he wants the pdf
def ccbt21001_page():
    workingdir = os.path.abspath(os.getcwd())
    filepath = workingdir + '/static/timetable/pdf_files/tt/'
    return send_from_directory(filepath, 'ccbt21001.pdf')

@app_001.route('/pdf_files/tt/ccec21001.pdf') #the url you'll send the user to when he wants the pdf
def ccec21001_page():
    workingdir = os.path.abspath(os.getcwd())
    filepath = workingdir + '/static/timetable/pdf_files/tt/'
    return send_from_directory(filepath, 'ccec21001.pdf')

@app_001.route('/pdf_files/tt/ccjn21001.pdf') #the url you'll send the user to when he wants the pdf
def pdfviewer():
    workingdir = os.path.abspath(os.getcwd())
    filepath = workingdir + '/static/timetable/pdf_files/tt/'
    return send_from_directory(filepath, 'ccjn21001.pdf')

@app_001.route('/pdf_files/tt/ccpd21001.pdf') #the url you'll send the user to when he wants the pdf
def ccpd21001_page():
    workingdir = os.path.abspath(os.getcwd())
    filepath = workingdir + '/static/timetable/pdf_files/tt/'
    return send_from_directory(filepath, 'ccpd21001.pdf')

@app_001.route('/pdf_files/tt/ccpm21001.pdf') #the url you'll send the user to when he wants the pdf
def ccpm21001_page():
    workingdir = os.path.abspath(os.getcwd())
    filepath = workingdir + '/static/timetable/pdf_files/tt/'
    return send_from_directory(filepath, 'ccpm21001.pdf')

@app_001.route('/pdf_files/tt/ccpp21001.pdf') #the url you'll send the user to when he wants the pdf
def ccpp21001_page():
    workingdir = os.path.abspath(os.getcwd())
    filepath = workingdir + '/static/timetable/pdf_files/tt/'
    return send_from_directory(filepath, 'ccpp21001.pdf')

@app_001.route('/pdf_files/tt/ccss21001.pdf') #the url you'll send the user to when he wants the pdf
def ccss21001_page():
    workingdir = os.path.abspath(os.getcwd())
    filepath = workingdir + '/static/timetable/pdf_files/tt/'
    return send_from_directory(filepath, 'ccss21001.pdf')

@app_001.route('/pdf_files/tt/dcba21001.pdf') #the url you'll send the user to when he wants the pdf
def dcba21001_page():
    workingdir = os.path.abspath(os.getcwd())
    filepath = workingdir + '/static/timetable/pdf_files/tt/'
    return send_from_directory(filepath, 'dcba21001.pdf')

@app_001.route('/pdf_files/tt/dcbp21001.pdf') #the url you'll send the user to when he wants the pdf
def dcbp21001_page():
    workingdir = os.path.abspath(os.getcwd())
    filepath = workingdir + '/static/timetable/pdf_files/tt/'
    return send_from_directory(filepath, 'dcbp21001.pdf')

@app_001.route('/pdf_files/tt/dcbp21002.pdf') #the url you'll send the user to when he wants the pdf
def dcbp21002_page():
    workingdir = os.path.abspath(os.getcwd())
    filepath = workingdir + '/static/timetable/pdf_files/tt/'
    return send_from_directory(filepath, 'dcbp21002.pdf')

@app_001.route('/pdf_files/tt/dcec21001.pdf') #the url you'll send the user to when he wants the pdf
def dcec21001_page():
    workingdir = os.path.abspath(os.getcwd())
    filepath = workingdir + '/static/timetable/pdf_files/tt/'
    return send_from_directory(filepath, 'dcec21001.pdf')

@app_001.route('/pdf_files/tt/dcec21002.pdf') #the url you'll send the user to when he wants the pdf
def dcec21002_page():
    workingdir = os.path.abspath(os.getcwd())
    filepath = workingdir + '/static/timetable/pdf_files/tt/'
    return send_from_directory(filepath, 'dcec21002.pdf')

@app_001.route('/pdf_files/tt/dcjn21001.pdf') #the url you'll send the user to when he wants the pdf
def dcjn21001_page():
    workingdir = os.path.abspath(os.getcwd())
    filepath = workingdir + '/static/timetable/pdf_files/tt/'
    return send_from_directory(filepath, 'dcjn21001.pdf')

@app_001.route('/pdf_files/tt/dcjn21002.pdf') #the url you'll send the user to when he wants the pdf
def dcjn21002_page():
    workingdir = os.path.abspath(os.getcwd())
    filepath = workingdir + '/static/timetable/pdf_files/tt/'
    return send_from_directory(filepath, 'dcjn21002.pdf')

@app_001.route('/pdf_files/tt/dcpd21001.pdf') #the url you'll send the user to when he wants the pdf
def dcpd21001_page():
    workingdir = os.path.abspath(os.getcwd())
    filepath = workingdir + '/static/timetable/pdf_files/tt/'
    return send_from_directory(filepath, 'dcpd21001.pdf')

@app_001.route('/pdf_files/tt/dcpd21002.pdf') #the url you'll send the user to when he wants the pdf
def dcpd21002_page():
    workingdir = os.path.abspath(os.getcwd())
    filepath = workingdir + '/static/timetable/pdf_files/tt/'
    return send_from_directory(filepath, 'dcpd21002.pdf')

@app_001.route('/pdf_files/tt/dcpm21001.pdf') #the url you'll send the user to when he wants the pdf
def dcpm21001_page():
    workingdir = os.path.abspath(os.getcwd())
    filepath = workingdir + '/static/timetable/pdf_files/tt/'
    return send_from_directory(filepath, 'dcpm21001.pdf')

@app_001.route('/pdf_files/tt/dcpp21001.pdf') #the url you'll send the user to when he wants the pdf
def dcpp21001_page():
    workingdir = os.path.abspath(os.getcwd())
    filepath = workingdir + '/static/timetable/pdf_files/tt/'
    return send_from_directory(filepath, 'dcpp21001.pdf')

@app_001.route('/pdf_files/tt/dcpp21002.pdf') #the url you'll send the user to when he wants the pdf
def dcpp21002_page():
    workingdir = os.path.abspath(os.getcwd())
    filepath = workingdir + '/static/timetable/pdf_files/tt/'
    return send_from_directory(filepath, 'dcpp21002.pdf')

@app_001.route('/pdf_files/tt/dcss21001.pdf') #the url you'll send the user to when he wants the pdf
def dcss21001_page():
    workingdir = os.path.abspath(os.getcwd())
    filepath = workingdir + '/static/timetable/pdf_files/tt/'
    return send_from_directory(filepath, 'dcss21001.pdf')

@app_001.route('/pdf_files/tt/dcss21002.pdf') #the url you'll send the user to when he wants the pdf
def dcss21002_page():
    workingdir = os.path.abspath(os.getcwd())
    filepath = workingdir + '/static/timetable/pdf_files/tt/'
    return send_from_directory(filepath, 'dcss21002.pdf')


#if __name__ == '__main__':
#    app.run(host='127.0.0.1', port=8080, debug=True)

timetable/templates/timetable/tt_cic_index.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-uWxY/CJNBR+1zjPWmfnSnVxwRheevXITnMqoEIeG1LJrdI0GlVs/9cVSyPYXdcSF" crossorigin="anonymous">

    <title>程 式 集</title>
    <script src="{{ url_for('static', filename='/mainhome/script.js') }}"></script>
    <link type="text/css" rel="stylesheet" href="{{ url_for('static', filename='/mainhome/style.css') }}">

  </head>

  <body>
    <nav class="navbar navbar-expand-md navbar-dark bg-dark">
        <a class="navbar-brand" href="{{ url_for('app_000.first_home_page') }}">程 式 集</a>

        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    <a class="nav-link" href="{{ url_for('app_000.first_home_page') }}">主 頁<span class="sr-only"></span></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('app_001.tt_index_page') }}">時 間 表</a>
                </li>
            </ul>
        </div>

    </nav>

    <p>&nbsp;</p>

    <h1>建造證書課程時間表</h1>

 <!--   <a href="/pdf_files/tt/0.pdf" class="button">建造文憑</a>

    <a href="/pdf_files/tt/0.pdf" class="button">建造證書</a>
-->

    <p>&nbsp;</p>
<h3>砌磚鋪瓦</h3>
<div class="btn-group" style="width:100%">
  <button style="width:100%"><a href="/pdf_files/tt/ccbt21001.pdf">CCBT21001</button></a>
</div>

    <p>&nbsp;</p>
<h3>細木工藝</h3>
<div class="btn-group" style="width:100%">
  <button style="width:100%"><a href="/pdf_files/tt/ccjn21001.pdf">CCJN21001</button></a>
</div>

    <p>&nbsp;</p>
<h3>油漆粉飾</h3>
    <div class="btn-group" style="width:100%">
    <button style="width:100%"><a href="/pdf_files/tt/ccpd21001.pdf">CCPD21001</button></a>
    </div>

    <p>&nbsp;</p>
<h3>機械維修</h3>
    <div class="btn-group" style="width:100%">
    <button style="width:100%"><a href="/pdf_files/tt/ccpm21001.pdf">CCPM21001</button></a>
    </div>

    <p>&nbsp;</p>
<h3>水喉</h3>
    <div class="btn-group" style="width:100%">
    <button style="width:100%"><a href="/pdf_files/tt/ccpp21001.pdf">CCPP21001</button></a>
    </div>

    <p>&nbsp;</p>
<h3>電力裝置</h3>
    <div class="btn-group" style="width:100%">
    <button style="width:100%"><a href="/pdf_files/tt/ccec21001.pdf">CCEC21001</button></a>
    </div>

    <p>&nbsp;</p>
<h3>工地測量</h3>
    <div class="btn-group" style="width:100%">
    <button style="width:100%"><a href="/pdf_files/tt/ccss21001.pdf">CCSS21001</button></a>
    </div>

      <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-kQtW33rZJAHjgefvhyyzcGF3C5TFyBQBA13V1RKPf4uH+bwyzQxZ6CmMZHmNBEfJ" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js" integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.2/dist/js/bootstrap.min.js" integrity="sha384-PsUw7Xwds7x08Ew3exXhqzbhuEYmA2xnwc8BuD6SEr+UmEHlX8/MCltYEodzWA4u" crossorigin="anonymous"></script>
    -->

  </body>

  <style>
    body {
        background-color: #212121;
        color: white
    }
  </style>


</html>

timetable/templates/timetable/tt_dic_index.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-uWxY/CJNBR+1zjPWmfnSnVxwRheevXITnMqoEIeG1LJrdI0GlVs/9cVSyPYXdcSF" crossorigin="anonymous">

    <title>程 式 集</title>
    <script src="{{ url_for('static', filename='/mainhome/script.js') }}"></script>
    <link type="text/css" rel="stylesheet" href="{{ url_for('static', filename='/mainhome/style.css') }}">

  </head>

  <body>
    <nav class="navbar navbar-expand-md navbar-dark bg-dark">
        <a class="navbar-brand" href="{{ url_for('app_000.first_home_page') }}">程 式 集</a>

        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    <a class="nav-link" href="{{ url_for('app_000.first_home_page') }}">主 頁<span class="sr-only"></span></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('app_001.tt_index_page') }}">時 間 表</a>
                </li>
            </ul>
        </div>

    </nav>

    <p>&nbsp;</p>

    <h1>建造文憑課程時間表</h1>

 <!--   <a href="/pdf_files/tt/0.pdf" class="button">建造文憑</a>

    <a href="/pdf_files/tt/0.pdf" class="button">建造證書</a>
-->

    <p>&nbsp;</p>
<h3>鋼筋屈紮</h3>
    <div class="btn-group" style="width:100%">
    <button style="width:100%"><a href="/pdf_files/tt/dcba21001.pdf">DCBA21001</button></a>
    </div>

    <p>&nbsp;</p>
<h3>泥水粉飾</h3>
<div class="btn-group" style="width:100%">
  <button style="width:50%"><a href="/pdf_files/tt/dcbp21001.pdf">DCBP21001</button></a>
  <button style="width:50%"><a href="/pdf_files/tt/dcbp21002.pdf">DCBP21002</button></a>
</div>

    <p>&nbsp;</p>
<h3>細木工藝</h3>
<div class="btn-group" style="width:100%">
  <button style="width:50%"><a href="/pdf_files/tt/dcjn21001.pdf">DCJN21001</button></a>
  <button style="width:50%"><a href="/pdf_files/tt/dcjn21002.pdf">DCJN21002</button></a>
</div>

    <p>&nbsp;</p>
<h3>油漆粉飾</h3>
    <div class="btn-group" style="width:100%">
    <button style="width:50%"><a href="/pdf_files/tt/dcpd21001.pdf">DCPD21001</button></a>
    <button style="width:50%"><a href="/pdf_files/tt/dcpd21002.pdf">DCPD21002</button></a>
    </div>

    <p>&nbsp;</p>
<h3>機械維修</h3>
    <div class="btn-group" style="width:100%">
    <button style="width:100%"><a href="/pdf_files/tt/dcpm21001.pdf">DCPM21001</button></a>
    </div>

    <p>&nbsp;</p>
<h3>水喉</h3>
    <div class="btn-group" style="width:100%">
    <button style="width:50%"><a href="/pdf_files/tt/dcpp21001.pdf">DCPP21001</button></a>
    <button style="width:50%"><a href="/pdf_files/tt/dcpp21002.pdf">DCPP21002</button></a>
    </div>

    <p>&nbsp;</p>
<h3>電力裝置</h3>
    <div class="btn-group" style="width:100%">
    <button style="width:50%"><a href="/pdf_files/tt/dcec21001.pdf">DCEC21001</button></a>
    <button style="width:50%"><a href="/pdf_files/tt/dcec21002.pdf">DCEC21002</button></a>
    </div>

    <p>&nbsp;</p>
<h3>工地測量</h3>
    <div class="btn-group" style="width:100%">
    <button style="width:50%"><a href="/pdf_files/tt/dcss21001.pdf">DCSS21001</button></a>
    <button style="width:50%"><a href="/pdf_files/tt/dcss21002.pdf">DCSS21002</button></a>
    </div>

    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-kQtW33rZJAHjgefvhyyzcGF3C5TFyBQBA13V1RKPf4uH+bwyzQxZ6CmMZHmNBEfJ" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js" integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.2/dist/js/bootstrap.min.js" integrity="sha384-PsUw7Xwds7x08Ew3exXhqzbhuEYmA2xnwc8BuD6SEr+UmEHlX8/MCltYEodzWA4u" crossorigin="anonymous"></script>
    -->

  </body>

  <style>
    body {
        background-color: #212121;
        color: white
    }
  </style>


</html>

timetable/templates/timetable/tt_index.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-uWxY/CJNBR+1zjPWmfnSnVxwRheevXITnMqoEIeG1LJrdI0GlVs/9cVSyPYXdcSF" crossorigin="anonymous">

    <title>程 式 集</title>
    <script src="{{ url_for('static', filename='/mainhome/script.js') }}"></script>
    <link type="text/css" rel="stylesheet" href="{{ url_for('static', filename='/mainhome/style.css') }}">

  </head>

  <body>
    <nav class="navbar navbar-expand-md navbar-dark bg-dark">

        <a class="navbar-brand" href="{{ url_for('app_000.first_home_page') }}">程 式 集</a>

        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    <a class="nav-link" href="{{ url_for('app_000.first_home_page') }}">主 頁<span class="sr-only"></span></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('app_001.tt_index_page') }}">時 間 表</a>
                </li>
            </ul>
        </div>

    </nav>




    <p></p>
    <p></p>
    <h1>時 間 表</h1>

    <p></p>
    <p></p>
    <p></p>
    <p></p>
    <a class="my-button" title="Relevant Title" href="\tt_dic_index">建造文憑</a><a class="my-button" title="Relevant Title" href="\tt_cic_index">建造證書</a>

    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-kQtW33rZJAHjgefvhyyzcGF3C5TFyBQBA13V1RKPf4uH+bwyzQxZ6CmMZHmNBEfJ" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js" integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.2/dist/js/bootstrap.min.js" integrity="sha384-PsUw7Xwds7x08Ew3exXhqzbhuEYmA2xnwc8BuD6SEr+UmEHlX8/MCltYEodzWA4u" crossorigin="anonymous"></script>
    -->

  </body>

  <style>
    body {
        background-color: #212121;
        color: white
    }
  </style>


</html>